### ISSUE TITLE
Dark-Mode not reacting 

### ISSUE THREAD

**Issue by kenshanta** [kenshanta/sh-url-t#20]

**Comment by Rodney1988** [comment]
hi there, maybe I can have a look at this? are there any infos I might require? like env data, etc

**Comment by kenshanta** [comment]
You can use mock data instead of fetching from the API. just checkout how `index.ejs` is working and adjust accordingly.
Regardless of data, the issue is in the CSS codebase itself. I have only opened this issue as a reminder to fix it later.

Let me know if you find anything interesting or if you need additional info.

**Comment by kenshanta** [comment]
Instead of adding a `Dark Mode` toggle, the new approach will automatically set the default theme based on the user's system preference.

Closing this issue.
